// Code generated by Fern. DO NOT EDIT.

package client

import (
	batch "github.com/getzep/zep-go/v4/batch"
	context "github.com/getzep/zep-go/v4/context"
	core "github.com/getzep/zep-go/v4/core"
	client "github.com/getzep/zep-go/v4/graph/client"
	internal "github.com/getzep/zep-go/v4/internal"
	option "github.com/getzep/zep-go/v4/option"
	project "github.com/getzep/zep-go/v4/project"
	task "github.com/getzep/zep-go/v4/task"
	threadclient "github.com/getzep/zep-go/v4/thread/client"
	user "github.com/getzep/zep-go/v4/user"
	usergroup "github.com/getzep/zep-go/v4/usergroup"
	http "net/http"
	os "os"
)

type Client struct {
	UserGroup *usergroup.Client
	Batch     *batch.Client
	Context   *context.Client
	Graph     *client.Client
	Project   *project.Client
	Task      *task.Client
	Thread    *threadclient.Client
	User      *user.Client

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("ZEP_API_KEY")
	}
	return &Client{
		UserGroup: usergroup.NewClient(opts...),
		Batch:     batch.NewClient(opts...),
		Context:   context.NewClient(opts...),
		Graph:     client.NewClient(opts...),
		Project:   project.NewClient(opts...),
		Task:      task.NewClient(opts...),
		Thread:    threadclient.NewClient(opts...),
		User:      user.NewClient(opts...),
		baseURL:   options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}
