// Code generated by Fern. DO NOT EDIT.

package lookup

import (
	context "context"
	os "os"

	zep "github.com/getzep/zep-go/v4"
	core "github.com/getzep/zep-go/v4/core"
	internal "github.com/getzep/zep-go/v4/internal"
	option "github.com/getzep/zep-go/v4/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("ZEP_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	request := &zep.BatchLookupRequest{}
//	client.Lookup.Batch(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Batch(
	ctx context.Context,
	request *zep.BatchLookupRequest,
	opts ...option.IdempotentRequestOption,
) (*zep.LookupBatchResponse, error) {
	response, err := c.WithRawResponse.Batch(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
