// Code generated by Fern. DO NOT EDIT.

package lookup

import (
	context "context"
	http "net/http"

	zep "github.com/getzep/zep-go/v4"
	core "github.com/getzep/zep-go/v4/core"
	internal "github.com/getzep/zep-go/v4/internal"
	option "github.com/getzep/zep-go/v4/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Batch(
	ctx context.Context,
	request *zep.BatchLookupRequest,
	opts ...option.IdempotentRequestOption,
) (*core.Response[*zep.LookupBatchResponse], error) {
	options := core.NewIdempotentRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.getzep.com/api/v4",
	)
	endpointURL := baseURL + "/lookup"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *zep.LookupBatchResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(zep.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*zep.LookupBatchResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
