// Code generated by Fern. DO NOT EDIT.

package zep

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/getzep/zep-go/v4/internal"
	big "math/big"
)

var (
	declareAgentBreakingChangeRequestFieldExpectedRevision = big.NewInt(1 << 0)
	declareAgentBreakingChangeRequestFieldVersion          = big.NewInt(1 << 1)
)

type DeclareAgentBreakingChangeRequest struct {
	ExpectedRevision int    `json:"expected_revision" url:"-"`
	Version          string `json:"version" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeclareAgentBreakingChangeRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetExpectedRevision sets the ExpectedRevision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeclareAgentBreakingChangeRequest) SetExpectedRevision(expectedRevision int) {
	d.ExpectedRevision = expectedRevision
	d.require(declareAgentBreakingChangeRequestFieldExpectedRevision)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeclareAgentBreakingChangeRequest) SetVersion(version string) {
	d.Version = version
	d.require(declareAgentBreakingChangeRequestFieldVersion)
}

func (d *DeclareAgentBreakingChangeRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DeclareAgentBreakingChangeRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DeclareAgentBreakingChangeRequest(body)
	return nil
}

func (d *DeclareAgentBreakingChangeRequest) MarshalJSON() ([]byte, error) {
	type embed DeclareAgentBreakingChangeRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteAgentRequestFieldExpectedRevision = big.NewInt(1 << 0)
)

type DeleteAgentRequest struct {
	// The current Agent revision used for optimistic concurrency.
	ExpectedRevision int `json:"expected_revision" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteAgentRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetExpectedRevision sets the ExpectedRevision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteAgentRequest) SetExpectedRevision(expectedRevision int) {
	d.ExpectedRevision = expectedRevision
	d.require(deleteAgentRequestFieldExpectedRevision)
}

func (d *DeleteAgentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteAgentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DeleteAgentRequest(body)
	return nil
}

func (d *DeleteAgentRequest) MarshalJSON() ([]byte, error) {
	type embed DeleteAgentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getAgentContextRequestFieldEnvironments   = big.NewInt(1 << 0)
	getAgentContextRequestFieldKind           = big.NewInt(1 << 1)
	getAgentContextRequestFieldMaxCharacters  = big.NewInt(1 << 2)
	getAgentContextRequestFieldModels         = big.NewInt(1 << 3)
	getAgentContextRequestFieldObjective      = big.NewInt(1 << 4)
	getAgentContextRequestFieldTaskFamily     = big.NewInt(1 << 5)
	getAgentContextRequestFieldTools          = big.NewInt(1 << 6)
	getAgentContextRequestFieldTrajectoryUUID = big.NewInt(1 << 7)
)

type GetAgentContextRequest struct {
	Environments   []*AgentContextResource `json:"environments,omitempty" url:"-"`
	Kind           *string                 `json:"kind,omitempty" url:"-"`
	MaxCharacters  *int                    `json:"max_characters,omitempty" url:"-"`
	Models         []*AgentContextResource `json:"models,omitempty" url:"-"`
	Objective      *string                 `json:"objective,omitempty" url:"-"`
	TaskFamily     *string                 `json:"task_family,omitempty" url:"-"`
	Tools          []*AgentContextResource `json:"tools,omitempty" url:"-"`
	TrajectoryUUID *string                 `json:"trajectory_uuid,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAgentContextRequest) require(field *big.Int) {
	next := new(big.Int)
	if g.explicitFields != nil {
		next.Set(g.explicitFields)
	}
	next.Or(next, field)
	g.explicitFields = next
}

// SetEnvironments sets the Environments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetEnvironments(environments []*AgentContextResource) {
	g.Environments = environments
	g.require(getAgentContextRequestFieldEnvironments)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetKind(kind *string) {
	g.Kind = kind
	g.require(getAgentContextRequestFieldKind)
}

// SetMaxCharacters sets the MaxCharacters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetMaxCharacters(maxCharacters *int) {
	g.MaxCharacters = maxCharacters
	g.require(getAgentContextRequestFieldMaxCharacters)
}

// SetModels sets the Models field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetModels(models []*AgentContextResource) {
	g.Models = models
	g.require(getAgentContextRequestFieldModels)
}

// SetObjective sets the Objective field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetObjective(objective *string) {
	g.Objective = objective
	g.require(getAgentContextRequestFieldObjective)
}

// SetTaskFamily sets the TaskFamily field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetTaskFamily(taskFamily *string) {
	g.TaskFamily = taskFamily
	g.require(getAgentContextRequestFieldTaskFamily)
}

// SetTools sets the Tools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetTools(tools []*AgentContextResource) {
	g.Tools = tools
	g.require(getAgentContextRequestFieldTools)
}

// SetTrajectoryUUID sets the TrajectoryUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAgentContextRequest) SetTrajectoryUUID(trajectoryUUID *string) {
	g.TrajectoryUUID = trajectoryUUID
	g.require(getAgentContextRequestFieldTrajectoryUUID)
}

func (g *GetAgentContextRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetAgentContextRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetAgentContextRequest(body)
	return nil
}

func (g *GetAgentContextRequest) MarshalJSON() ([]byte, error) {
	type embed GetAgentContextRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	agentListRequestFieldLimit        = big.NewInt(1 << 0)
	agentListRequestFieldCursor       = big.NewInt(1 << 1)
	agentListRequestFieldAgentID      = big.NewInt(1 << 2)
	agentListRequestFieldDeploymentID = big.NewInt(1 << 3)
	agentListRequestFieldMetadata     = big.NewInt(1 << 4)
	agentListRequestFieldStatus       = big.NewInt(1 << 5)
	agentListRequestFieldVersion      = big.NewInt(1 << 6)
)

type AgentListRequest struct {
	// Page size (maximum 100)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Filters to the exact developer-assigned Agent identifier.
	AgentID *string `json:"agent_id,omitempty" url:"-"`
	// Filters to the exact deployment identifier.
	DeploymentID *string `json:"deployment_id,omitempty" url:"-"`
	// Filters to Agents whose metadata contains these key-value pairs.
	Metadata map[string]any `json:"metadata,omitempty" url:"-"`
	// Filters to lifecycle status. Omit to include every status.
	Status *AgentStatus `json:"status,omitempty" url:"-"`
	// Filters to the exact deployment version.
	Version *string `json:"version,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AgentListRequest) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListRequest) SetLimit(limit *int) {
	a.Limit = limit
	a.require(agentListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListRequest) SetCursor(cursor *string) {
	a.Cursor = cursor
	a.require(agentListRequestFieldCursor)
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListRequest) SetAgentID(agentID *string) {
	a.AgentID = agentID
	a.require(agentListRequestFieldAgentID)
}

// SetDeploymentID sets the DeploymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListRequest) SetDeploymentID(deploymentID *string) {
	a.DeploymentID = deploymentID
	a.require(agentListRequestFieldDeploymentID)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListRequest) SetMetadata(metadata map[string]any) {
	a.Metadata = metadata
	a.require(agentListRequestFieldMetadata)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListRequest) SetStatus(status *AgentStatus) {
	a.Status = status
	a.require(agentListRequestFieldStatus)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentListRequest) SetVersion(version *string) {
	a.Version = version
	a.require(agentListRequestFieldVersion)
}

func (a *AgentListRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentListRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AgentListRequest(body)
	return nil
}

func (a *AgentListRequest) MarshalJSON() ([]byte, error) {
	type embed AgentListRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	agentFieldAgentID        = big.NewInt(1 << 0)
	agentFieldCreatedAt      = big.NewInt(1 << 1)
	agentFieldDeploymentID   = big.NewInt(1 << 2)
	agentFieldDescription    = big.NewInt(1 << 3)
	agentFieldMemorySettings = big.NewInt(1 << 4)
	agentFieldMetadata       = big.NewInt(1 << 5)
	agentFieldName           = big.NewInt(1 << 6)
	agentFieldRevision       = big.NewInt(1 << 7)
	agentFieldSecurityDomain = big.NewInt(1 << 8)
	agentFieldStatus         = big.NewInt(1 << 9)
	agentFieldUpdatedAt      = big.NewInt(1 << 10)
	agentFieldUUID           = big.NewInt(1 << 11)
	agentFieldVersion        = big.NewInt(1 << 12)
)

type Agent struct {
	// The developer-assigned Agent identifier, unique within the project.
	AgentID *string `json:"agent_id,omitempty" url:"agent_id,omitempty"`
	// The time the Agent was created.
	CreatedAt *string `json:"created_at,omitempty" url:"created_at,omitempty"`
	// The customer deployment this Agent represents.
	DeploymentID *string `json:"deployment_id,omitempty" url:"deployment_id,omitempty"`
	// A human-readable description of the Agent.
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	// Agent Memory capture, compilation, and promotion settings.
	MemorySettings *AgentMemorySettings `json:"memory_settings,omitempty" url:"memory_settings,omitempty"`
	// Developer metadata used to organize and filter Agents.
	Metadata map[string]any `json:"metadata,omitempty" url:"metadata,omitempty"`
	// The Agent's display name.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The revision required by the next update or delete request.
	Revision *int `json:"revision,omitempty" url:"revision,omitempty"`
	// The immutable boundary within which Skills may be synthesized.
	SecurityDomain *string `json:"security_domain,omitempty" url:"security_domain,omitempty"`
	// The current lifecycle status.
	Status *AgentStatus `json:"status,omitempty" url:"status,omitempty"`
	// The time the Agent was last updated.
	UpdatedAt *string `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	// The stable identifier of the Agent.
	UUID *string `json:"uuid,omitempty" url:"uuid,omitempty"`
	// The customer deployment version this Agent represents.
	Version *string `json:"version,omitempty" url:"version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *Agent) GetAgentID() *string {
	if a == nil {
		return nil
	}
	return a.AgentID
}

func (a *Agent) GetCreatedAt() *string {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *Agent) GetDeploymentID() *string {
	if a == nil {
		return nil
	}
	return a.DeploymentID
}

func (a *Agent) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *Agent) GetMemorySettings() *AgentMemorySettings {
	if a == nil {
		return nil
	}
	return a.MemorySettings
}

func (a *Agent) GetMetadata() map[string]any {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *Agent) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *Agent) GetRevision() *int {
	if a == nil {
		return nil
	}
	return a.Revision
}

func (a *Agent) GetSecurityDomain() *string {
	if a == nil {
		return nil
	}
	return a.SecurityDomain
}

func (a *Agent) GetStatus() *AgentStatus {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *Agent) GetUpdatedAt() *string {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *Agent) GetUUID() *string {
	if a == nil {
		return nil
	}
	return a.UUID
}

func (a *Agent) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}

func (a *Agent) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *Agent) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetAgentID sets the AgentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetAgentID(agentID *string) {
	a.AgentID = agentID
	a.require(agentFieldAgentID)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetCreatedAt(createdAt *string) {
	a.CreatedAt = createdAt
	a.require(agentFieldCreatedAt)
}

// SetDeploymentID sets the DeploymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetDeploymentID(deploymentID *string) {
	a.DeploymentID = deploymentID
	a.require(agentFieldDeploymentID)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetDescription(description *string) {
	a.Description = description
	a.require(agentFieldDescription)
}

// SetMemorySettings sets the MemorySettings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetMemorySettings(memorySettings *AgentMemorySettings) {
	a.MemorySettings = memorySettings
	a.require(agentFieldMemorySettings)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetMetadata(metadata map[string]any) {
	a.Metadata = metadata
	a.require(agentFieldMetadata)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetName(name *string) {
	a.Name = name
	a.require(agentFieldName)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetRevision(revision *int) {
	a.Revision = revision
	a.require(agentFieldRevision)
}

// SetSecurityDomain sets the SecurityDomain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetSecurityDomain(securityDomain *string) {
	a.SecurityDomain = securityDomain
	a.require(agentFieldSecurityDomain)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetStatus(status *AgentStatus) {
	a.Status = status
	a.require(agentFieldStatus)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetUpdatedAt(updatedAt *string) {
	a.UpdatedAt = updatedAt
	a.require(agentFieldUpdatedAt)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetUUID(uuid *string) {
	a.UUID = uuid
	a.require(agentFieldUUID)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *Agent) SetVersion(version *string) {
	a.Version = version
	a.require(agentFieldVersion)
}

func (a *Agent) UnmarshalJSON(data []byte) error {
	type unmarshaler Agent
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = Agent(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *Agent) MarshalJSON() ([]byte, error) {
	type embed Agent
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *Agent) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentBreakingChangeFieldAffectedSkillCount = big.NewInt(1 << 0)
	agentBreakingChangeFieldAgentUUID          = big.NewInt(1 << 1)
	agentBreakingChangeFieldRevision           = big.NewInt(1 << 2)
	agentBreakingChangeFieldUUID               = big.NewInt(1 << 3)
	agentBreakingChangeFieldVersion            = big.NewInt(1 << 4)
)

type AgentBreakingChange struct {
	AffectedSkillCount *int    `json:"affected_skill_count,omitempty" url:"affected_skill_count,omitempty"`
	AgentUUID          *string `json:"agent_uuid,omitempty" url:"agent_uuid,omitempty"`
	// The Agent revision produced by this declaration, stable on replay.
	Revision *int    `json:"revision,omitempty" url:"revision,omitempty"`
	UUID     *string `json:"uuid,omitempty" url:"uuid,omitempty"`
	Version  *string `json:"version,omitempty" url:"version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentBreakingChange) GetAffectedSkillCount() *int {
	if a == nil {
		return nil
	}
	return a.AffectedSkillCount
}

func (a *AgentBreakingChange) GetAgentUUID() *string {
	if a == nil {
		return nil
	}
	return a.AgentUUID
}

func (a *AgentBreakingChange) GetRevision() *int {
	if a == nil {
		return nil
	}
	return a.Revision
}

func (a *AgentBreakingChange) GetUUID() *string {
	if a == nil {
		return nil
	}
	return a.UUID
}

func (a *AgentBreakingChange) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}

func (a *AgentBreakingChange) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentBreakingChange) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetAffectedSkillCount sets the AffectedSkillCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentBreakingChange) SetAffectedSkillCount(affectedSkillCount *int) {
	a.AffectedSkillCount = affectedSkillCount
	a.require(agentBreakingChangeFieldAffectedSkillCount)
}

// SetAgentUUID sets the AgentUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentBreakingChange) SetAgentUUID(agentUUID *string) {
	a.AgentUUID = agentUUID
	a.require(agentBreakingChangeFieldAgentUUID)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentBreakingChange) SetRevision(revision *int) {
	a.Revision = revision
	a.require(agentBreakingChangeFieldRevision)
}

// SetUUID sets the UUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentBreakingChange) SetUUID(uuid *string) {
	a.UUID = uuid
	a.require(agentBreakingChangeFieldUUID)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentBreakingChange) SetVersion(version *string) {
	a.Version = version
	a.require(agentBreakingChangeFieldVersion)
}

func (a *AgentBreakingChange) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentBreakingChange
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentBreakingChange(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentBreakingChange) MarshalJSON() ([]byte, error) {
	type embed AgentBreakingChange
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentBreakingChange) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentContextFieldContext        = big.NewInt(1 << 0)
	agentContextFieldObjective      = big.NewInt(1 << 1)
	agentContextFieldPartialSources = big.NewInt(1 << 2)
	agentContextFieldRequestID      = big.NewInt(1 << 3)
	agentContextFieldSkipped        = big.NewInt(1 << 4)
	agentContextFieldSnapshot       = big.NewInt(1 << 5)
	agentContextFieldTaskFamily     = big.NewInt(1 << 6)
	agentContextFieldTrajectoryUUID = big.NewInt(1 << 7)
	agentContextFieldTruncated      = big.NewInt(1 << 8)
)

type AgentContext struct {
	Context        *string                      `json:"context,omitempty" url:"context,omitempty"`
	Objective      *string                      `json:"objective,omitempty" url:"objective,omitempty"`
	PartialSources []*AgentContextPartialSource `json:"partial_sources,omitempty" url:"partial_sources,omitempty"`
	RequestID      *string                      `json:"request_id,omitempty" url:"request_id,omitempty"`
	Skipped        []*AgentContextSkippedSkill  `json:"skipped,omitempty" url:"skipped,omitempty"`
	Snapshot       []*AgentContextSkillSnapshot `json:"snapshot,omitempty" url:"snapshot,omitempty"`
	TaskFamily     *string                      `json:"task_family,omitempty" url:"task_family,omitempty"`
	TrajectoryUUID *string                      `json:"trajectory_uuid,omitempty" url:"trajectory_uuid,omitempty"`
	Truncated      *bool                        `json:"truncated,omitempty" url:"truncated,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentContext) GetContext() *string {
	if a == nil {
		return nil
	}
	return a.Context
}

func (a *AgentContext) GetObjective() *string {
	if a == nil {
		return nil
	}
	return a.Objective
}

func (a *AgentContext) GetPartialSources() []*AgentContextPartialSource {
	if a == nil {
		return nil
	}
	return a.PartialSources
}

func (a *AgentContext) GetRequestID() *string {
	if a == nil {
		return nil
	}
	return a.RequestID
}

func (a *AgentContext) GetSkipped() []*AgentContextSkippedSkill {
	if a == nil {
		return nil
	}
	return a.Skipped
}

func (a *AgentContext) GetSnapshot() []*AgentContextSkillSnapshot {
	if a == nil {
		return nil
	}
	return a.Snapshot
}

func (a *AgentContext) GetTaskFamily() *string {
	if a == nil {
		return nil
	}
	return a.TaskFamily
}

func (a *AgentContext) GetTrajectoryUUID() *string {
	if a == nil {
		return nil
	}
	return a.TrajectoryUUID
}

func (a *AgentContext) GetTruncated() *bool {
	if a == nil {
		return nil
	}
	return a.Truncated
}

func (a *AgentContext) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentContext) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetContext sets the Context field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetContext(context *string) {
	a.Context = context
	a.require(agentContextFieldContext)
}

// SetObjective sets the Objective field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetObjective(objective *string) {
	a.Objective = objective
	a.require(agentContextFieldObjective)
}

// SetPartialSources sets the PartialSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetPartialSources(partialSources []*AgentContextPartialSource) {
	a.PartialSources = partialSources
	a.require(agentContextFieldPartialSources)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetRequestID(requestID *string) {
	a.RequestID = requestID
	a.require(agentContextFieldRequestID)
}

// SetSkipped sets the Skipped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetSkipped(skipped []*AgentContextSkippedSkill) {
	a.Skipped = skipped
	a.require(agentContextFieldSkipped)
}

// SetSnapshot sets the Snapshot field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetSnapshot(snapshot []*AgentContextSkillSnapshot) {
	a.Snapshot = snapshot
	a.require(agentContextFieldSnapshot)
}

// SetTaskFamily sets the TaskFamily field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetTaskFamily(taskFamily *string) {
	a.TaskFamily = taskFamily
	a.require(agentContextFieldTaskFamily)
}

// SetTrajectoryUUID sets the TrajectoryUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetTrajectoryUUID(trajectoryUUID *string) {
	a.TrajectoryUUID = trajectoryUUID
	a.require(agentContextFieldTrajectoryUUID)
}

// SetTruncated sets the Truncated field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContext) SetTruncated(truncated *bool) {
	a.Truncated = truncated
	a.require(agentContextFieldTruncated)
}

func (a *AgentContext) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentContext
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentContext(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentContext) MarshalJSON() ([]byte, error) {
	type embed AgentContext
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentContext) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentContextEvidenceCountsFieldContradicting = big.NewInt(1 << 0)
	agentContextEvidenceCountsFieldNeutral       = big.NewInt(1 << 1)
	agentContextEvidenceCountsFieldSupporting    = big.NewInt(1 << 2)
)

type AgentContextEvidenceCounts struct {
	Contradicting *int `json:"contradicting,omitempty" url:"contradicting,omitempty"`
	Neutral       *int `json:"neutral,omitempty" url:"neutral,omitempty"`
	Supporting    *int `json:"supporting,omitempty" url:"supporting,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentContextEvidenceCounts) GetContradicting() *int {
	if a == nil {
		return nil
	}
	return a.Contradicting
}

func (a *AgentContextEvidenceCounts) GetNeutral() *int {
	if a == nil {
		return nil
	}
	return a.Neutral
}

func (a *AgentContextEvidenceCounts) GetSupporting() *int {
	if a == nil {
		return nil
	}
	return a.Supporting
}

func (a *AgentContextEvidenceCounts) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentContextEvidenceCounts) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetContradicting sets the Contradicting field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextEvidenceCounts) SetContradicting(contradicting *int) {
	a.Contradicting = contradicting
	a.require(agentContextEvidenceCountsFieldContradicting)
}

// SetNeutral sets the Neutral field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextEvidenceCounts) SetNeutral(neutral *int) {
	a.Neutral = neutral
	a.require(agentContextEvidenceCountsFieldNeutral)
}

// SetSupporting sets the Supporting field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextEvidenceCounts) SetSupporting(supporting *int) {
	a.Supporting = supporting
	a.require(agentContextEvidenceCountsFieldSupporting)
}

func (a *AgentContextEvidenceCounts) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentContextEvidenceCounts
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentContextEvidenceCounts(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentContextEvidenceCounts) MarshalJSON() ([]byte, error) {
	type embed AgentContextEvidenceCounts
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentContextEvidenceCounts) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentContextPartialSourceFieldReason   = big.NewInt(1 << 0)
	agentContextPartialSourceFieldSource   = big.NewInt(1 << 1)
	agentContextPartialSourceFieldTaskUUID = big.NewInt(1 << 2)
)

type AgentContextPartialSource struct {
	Reason   *string `json:"reason,omitempty" url:"reason,omitempty"`
	Source   *string `json:"source,omitempty" url:"source,omitempty"`
	TaskUUID *string `json:"task_uuid,omitempty" url:"task_uuid,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentContextPartialSource) GetReason() *string {
	if a == nil {
		return nil
	}
	return a.Reason
}

func (a *AgentContextPartialSource) GetSource() *string {
	if a == nil {
		return nil
	}
	return a.Source
}

func (a *AgentContextPartialSource) GetTaskUUID() *string {
	if a == nil {
		return nil
	}
	return a.TaskUUID
}

func (a *AgentContextPartialSource) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentContextPartialSource) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextPartialSource) SetReason(reason *string) {
	a.Reason = reason
	a.require(agentContextPartialSourceFieldReason)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextPartialSource) SetSource(source *string) {
	a.Source = source
	a.require(agentContextPartialSourceFieldSource)
}

// SetTaskUUID sets the TaskUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextPartialSource) SetTaskUUID(taskUUID *string) {
	a.TaskUUID = taskUUID
	a.require(agentContextPartialSourceFieldTaskUUID)
}

func (a *AgentContextPartialSource) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentContextPartialSource
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentContextPartialSource(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentContextPartialSource) MarshalJSON() ([]byte, error) {
	type embed AgentContextPartialSource
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentContextPartialSource) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentContextResourceFieldName    = big.NewInt(1 << 0)
	agentContextResourceFieldVersion = big.NewInt(1 << 1)
)

type AgentContextResource struct {
	Name    string  `json:"name" url:"name"`
	Version *string `json:"version,omitempty" url:"version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentContextResource) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentContextResource) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}

func (a *AgentContextResource) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentContextResource) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextResource) SetName(name string) {
	a.Name = name
	a.require(agentContextResourceFieldName)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextResource) SetVersion(version *string) {
	a.Version = version
	a.require(agentContextResourceFieldVersion)
}

func (a *AgentContextResource) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentContextResource
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentContextResource(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentContextResource) MarshalJSON() ([]byte, error) {
	type embed AgentContextResource
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentContextResource) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentContextSkillSnapshotFieldArtifactSha256    = big.NewInt(1 << 0)
	agentContextSkillSnapshotFieldEvidenceCitations = big.NewInt(1 << 1)
	agentContextSkillSnapshotFieldEvidenceCounts    = big.NewInt(1 << 2)
	agentContextSkillSnapshotFieldRank              = big.NewInt(1 << 3)
	agentContextSkillSnapshotFieldSkillUUID         = big.NewInt(1 << 4)
	agentContextSkillSnapshotFieldVersion           = big.NewInt(1 << 5)
)

type AgentContextSkillSnapshot struct {
	ArtifactSha256    *string                     `json:"artifact_sha256,omitempty" url:"artifact_sha256,omitempty"`
	EvidenceCitations []string                    `json:"evidence_citations,omitempty" url:"evidence_citations,omitempty"`
	EvidenceCounts    *AgentContextEvidenceCounts `json:"evidence_counts,omitempty" url:"evidence_counts,omitempty"`
	Rank              *int                        `json:"rank,omitempty" url:"rank,omitempty"`
	SkillUUID         *string                     `json:"skill_uuid,omitempty" url:"skill_uuid,omitempty"`
	Version           *int                        `json:"version,omitempty" url:"version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentContextSkillSnapshot) GetArtifactSha256() *string {
	if a == nil {
		return nil
	}
	return a.ArtifactSha256
}

func (a *AgentContextSkillSnapshot) GetEvidenceCitations() []string {
	if a == nil {
		return nil
	}
	return a.EvidenceCitations
}

func (a *AgentContextSkillSnapshot) GetEvidenceCounts() *AgentContextEvidenceCounts {
	if a == nil {
		return nil
	}
	return a.EvidenceCounts
}

func (a *AgentContextSkillSnapshot) GetRank() *int {
	if a == nil {
		return nil
	}
	return a.Rank
}

func (a *AgentContextSkillSnapshot) GetSkillUUID() *string {
	if a == nil {
		return nil
	}
	return a.SkillUUID
}

func (a *AgentContextSkillSnapshot) GetVersion() *int {
	if a == nil {
		return nil
	}
	return a.Version
}

func (a *AgentContextSkillSnapshot) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentContextSkillSnapshot) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetArtifactSha256 sets the ArtifactSha256 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkillSnapshot) SetArtifactSha256(artifactSha256 *string) {
	a.ArtifactSha256 = artifactSha256
	a.require(agentContextSkillSnapshotFieldArtifactSha256)
}

// SetEvidenceCitations sets the EvidenceCitations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkillSnapshot) SetEvidenceCitations(evidenceCitations []string) {
	a.EvidenceCitations = evidenceCitations
	a.require(agentContextSkillSnapshotFieldEvidenceCitations)
}

// SetEvidenceCounts sets the EvidenceCounts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkillSnapshot) SetEvidenceCounts(evidenceCounts *AgentContextEvidenceCounts) {
	a.EvidenceCounts = evidenceCounts
	a.require(agentContextSkillSnapshotFieldEvidenceCounts)
}

// SetRank sets the Rank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkillSnapshot) SetRank(rank *int) {
	a.Rank = rank
	a.require(agentContextSkillSnapshotFieldRank)
}

// SetSkillUUID sets the SkillUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkillSnapshot) SetSkillUUID(skillUUID *string) {
	a.SkillUUID = skillUUID
	a.require(agentContextSkillSnapshotFieldSkillUUID)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkillSnapshot) SetVersion(version *int) {
	a.Version = version
	a.require(agentContextSkillSnapshotFieldVersion)
}

func (a *AgentContextSkillSnapshot) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentContextSkillSnapshot
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentContextSkillSnapshot(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentContextSkillSnapshot) MarshalJSON() ([]byte, error) {
	type embed AgentContextSkillSnapshot
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentContextSkillSnapshot) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentContextSkippedSkillFieldReason    = big.NewInt(1 << 0)
	agentContextSkippedSkillFieldSkillUUID = big.NewInt(1 << 1)
	agentContextSkippedSkillFieldVersion   = big.NewInt(1 << 2)
)

type AgentContextSkippedSkill struct {
	Reason    *string `json:"reason,omitempty" url:"reason,omitempty"`
	SkillUUID *string `json:"skill_uuid,omitempty" url:"skill_uuid,omitempty"`
	Version   *int    `json:"version,omitempty" url:"version,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentContextSkippedSkill) GetReason() *string {
	if a == nil {
		return nil
	}
	return a.Reason
}

func (a *AgentContextSkippedSkill) GetSkillUUID() *string {
	if a == nil {
		return nil
	}
	return a.SkillUUID
}

func (a *AgentContextSkippedSkill) GetVersion() *int {
	if a == nil {
		return nil
	}
	return a.Version
}

func (a *AgentContextSkippedSkill) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentContextSkippedSkill) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkippedSkill) SetReason(reason *string) {
	a.Reason = reason
	a.require(agentContextSkippedSkillFieldReason)
}

// SetSkillUUID sets the SkillUUID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkippedSkill) SetSkillUUID(skillUUID *string) {
	a.SkillUUID = skillUUID
	a.require(agentContextSkippedSkillFieldSkillUUID)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentContextSkippedSkill) SetVersion(version *int) {
	a.Version = version
	a.require(agentContextSkippedSkillFieldVersion)
}

func (a *AgentContextSkippedSkill) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentContextSkippedSkill
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentContextSkippedSkill(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentContextSkippedSkill) MarshalJSON() ([]byte, error) {
	type embed AgentContextSkippedSkill
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentContextSkippedSkill) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentDeleteResultFieldTask = big.NewInt(1 << 0)
)

type AgentDeleteResult struct {
	// The asynchronous task that tracks the Agent's deletion.
	Task *Task `json:"task,omitempty" url:"task,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentDeleteResult) GetTask() *Task {
	if a == nil {
		return nil
	}
	return a.Task
}

func (a *AgentDeleteResult) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentDeleteResult) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetTask sets the Task field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentDeleteResult) SetTask(task *Task) {
	a.Task = task
	a.require(agentDeleteResultFieldTask)
}

func (a *AgentDeleteResult) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentDeleteResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentDeleteResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentDeleteResult) MarshalJSON() ([]byte, error) {
	type embed AgentDeleteResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentDeleteResult) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	agentPageFieldItems      = big.NewInt(1 << 0)
	agentPageFieldNextCursor = big.NewInt(1 << 1)
	agentPageFieldTotalSize  = big.NewInt(1 << 2)
)

type AgentPage struct {
	// The Agents on this page.
	Items []*Agent `json:"items,omitempty" url:"items,omitempty"`
	// Opaque cursor for retrieving the next page, present only when more results
	// are available.
	NextCursor *string `json:"next_cursor,omitempty" url:"next_cursor,omitempty"`
	// The total number of Agents matching the filters and authorization scope.
	TotalSize *int `json:"total_size,omitempty" url:"total_size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AgentPage) GetItems() []*Agent {
	if a == nil {
		return nil
	}
	return a.Items
}

func (a *AgentPage) GetNextCursor() *string {
	if a == nil {
		return nil
	}
	return a.NextCursor
}

func (a *AgentPage) GetTotalSize() *int {
	if a == nil {
		return nil
	}
	return a.TotalSize
}

func (a *AgentPage) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AgentPage) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetItems sets the Items field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPage) SetItems(items []*Agent) {
	a.Items = items
	a.require(agentPageFieldItems)
}

// SetNextCursor sets the NextCursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPage) SetNextCursor(nextCursor *string) {
	a.NextCursor = nextCursor
	a.require(agentPageFieldNextCursor)
}

// SetTotalSize sets the TotalSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentPage) SetTotalSize(totalSize *int) {
	a.TotalSize = totalSize
	a.require(agentPageFieldTotalSize)
}

func (a *AgentPage) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentPage
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AgentPage(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AgentPage) MarshalJSON() ([]byte, error) {
	type embed AgentPage
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AgentPage) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type AgentStatus string

const (
	AgentStatusActive         AgentStatus = "active"
	AgentStatusDeleting       AgentStatus = "deleting"
	AgentStatusDeletionFailed AgentStatus = "deletion_failed"
)

func NewAgentStatusFromString(s string) (AgentStatus, error) {
	switch s {
	case "active":
		return AgentStatusActive, nil
	case "deleting":
		return AgentStatusDeleting, nil
	case "deletion_failed":
		return AgentStatusDeletionFailed, nil
	}
	var t AgentStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentStatus) Ptr() *AgentStatus {
	return &a
}

var (
	patchAgentRequestFieldDeploymentID     = big.NewInt(1 << 0)
	patchAgentRequestFieldDescription      = big.NewInt(1 << 1)
	patchAgentRequestFieldExpectedRevision = big.NewInt(1 << 2)
	patchAgentRequestFieldMemorySettings   = big.NewInt(1 << 3)
	patchAgentRequestFieldMetadata         = big.NewInt(1 << 4)
	patchAgentRequestFieldName             = big.NewInt(1 << 5)
	patchAgentRequestFieldVersion          = big.NewInt(1 << 6)
)

type PatchAgentRequest struct {
	// The customer deployment this Agent represents. Set to null to clear it.
	DeploymentID *string `json:"deployment_id,omitempty" url:"-"`
	// A human-readable description of the Agent. Set to null to clear it.
	Description *string `json:"description,omitempty" url:"-"`
	// The current Agent revision used for optimistic concurrency.
	ExpectedRevision int `json:"expected_revision" url:"-"`
	// Replacement Agent Memory settings. Set to null to restore defaults.
	MemorySettings *AgentMemorySettings `json:"memory_settings,omitempty" url:"-"`
	// Replacement developer metadata. Set to null to clear it.
	Metadata map[string]any `json:"metadata,omitempty" url:"-"`
	// The Agent's display name.
	Name *string `json:"name,omitempty" url:"-"`
	// The customer deployment version this Agent represents. Set to null to clear it.
	Version *string `json:"version,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PatchAgentRequest) require(field *big.Int) {
	next := new(big.Int)
	if p.explicitFields != nil {
		next.Set(p.explicitFields)
	}
	next.Or(next, field)
	p.explicitFields = next
}

// SetDeploymentID sets the DeploymentID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchAgentRequest) SetDeploymentID(deploymentID *string) {
	p.DeploymentID = deploymentID
	p.require(patchAgentRequestFieldDeploymentID)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchAgentRequest) SetDescription(description *string) {
	p.Description = description
	p.require(patchAgentRequestFieldDescription)
}

// SetExpectedRevision sets the ExpectedRevision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchAgentRequest) SetExpectedRevision(expectedRevision int) {
	p.ExpectedRevision = expectedRevision
	p.require(patchAgentRequestFieldExpectedRevision)
}

// SetMemorySettings sets the MemorySettings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchAgentRequest) SetMemorySettings(memorySettings *AgentMemorySettings) {
	p.MemorySettings = memorySettings
	p.require(patchAgentRequestFieldMemorySettings)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchAgentRequest) SetMetadata(metadata map[string]any) {
	p.Metadata = metadata
	p.require(patchAgentRequestFieldMetadata)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchAgentRequest) SetName(name *string) {
	p.Name = name
	p.require(patchAgentRequestFieldName)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchAgentRequest) SetVersion(version *string) {
	p.Version = version
	p.require(patchAgentRequestFieldVersion)
}

func (p *PatchAgentRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PatchAgentRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PatchAgentRequest(body)
	return nil
}

func (p *PatchAgentRequest) MarshalJSON() ([]byte, error) {
	type embed PatchAgentRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}
