// This file was auto-generated by Fern from our API Definition.

package zep

type GetDocumentListRequest struct {
	DocumentIDs []string `json:"document_ids,omitempty" url:"document_ids,omitempty"`
	UUIDs       []string `json:"uuids,omitempty" url:"uuids,omitempty"`
}

type DocumentSearchPayload struct {
	// Limit the number of returned documents
	Limit          *int                   `json:"-" url:"limit,omitempty"`
	CollectionName *string                `json:"collection_name,omitempty" url:"collection_name,omitempty"`
	Embedding      []float64              `json:"embedding,omitempty" url:"embedding,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
	// TODO: implement for documents
	MinScore   *float64    `json:"min_score,omitempty" url:"min_score,omitempty"`
	MmrLambda  *float64    `json:"mmr_lambda,omitempty" url:"mmr_lambda,omitempty"`
	SearchType *SearchType `json:"search_type,omitempty" url:"search_type,omitempty"`
	Text       *string     `json:"text,omitempty" url:"text,omitempty"`
}

type UpdateDocumentRequest struct {
	DocumentID *string                `json:"document_id,omitempty" url:"document_id,omitempty"`
	Metadata   map[string]interface{} `json:"metadata,omitempty" url:"metadata,omitempty"`
}
