// This file was auto-generated by Fern from our API Definition.

package zep

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/getzep/zep-go/v2/internal"
)

type AddDataRequest struct {
	CreatedAt         *string       `json:"created_at,omitempty" url:"-"`
	Data              string        `json:"data" url:"-"`
	GroupID           *string       `json:"group_id,omitempty" url:"-"`
	SourceDescription *string       `json:"source_description,omitempty" url:"-"`
	Type              GraphDataType `json:"type" url:"-"`
	UserID            *string       `json:"user_id,omitempty" url:"-"`
}

type AddDataBatchRequest struct {
	Episodes []*EpisodeData `json:"episodes,omitempty" url:"-"`
	GroupID  *string        `json:"group_id,omitempty" url:"-"`
	UserID   *string        `json:"user_id,omitempty" url:"-"`
}

type AddTripleRequest struct {
	// The timestamp of the message
	CreatedAt *string `json:"created_at,omitempty" url:"-"`
	// The time (if any) at which the edge expires
	ExpiredAt *string `json:"expired_at,omitempty" url:"-"`
	// The fact relating the two nodes that this edge represents
	Fact string `json:"fact" url:"-"`
	// The name of the edge to add. Should be all caps using snake case (eg RELATES_TO)
	FactName string `json:"fact_name" url:"-"`
	// The uuid of the edge to add
	FactUUID *string `json:"fact_uuid,omitempty" url:"-"`
	GroupID  *string `json:"group_id,omitempty" url:"-"`
	// The time (if any) at which the fact stops being true
	InvalidAt *string `json:"invalid_at,omitempty" url:"-"`
	// The name of the source node to add
	SourceNodeName *string `json:"source_node_name,omitempty" url:"-"`
	// The summary of the source node to add
	SourceNodeSummary *string `json:"source_node_summary,omitempty" url:"-"`
	// The source node uuid
	SourceNodeUUID *string `json:"source_node_uuid,omitempty" url:"-"`
	// The name of the target node to add
	TargetNodeName string `json:"target_node_name" url:"-"`
	// The summary of the target node to add
	TargetNodeSummary *string `json:"target_node_summary,omitempty" url:"-"`
	// The target node uuid
	TargetNodeUUID *string `json:"target_node_uuid,omitempty" url:"-"`
	UserID         *string `json:"user_id,omitempty" url:"-"`
	// The time at which the fact becomes true
	ValidAt *string `json:"valid_at,omitempty" url:"-"`
}

type GraphSearchQuery struct {
	// Node to rerank around for node distance reranking
	CenterNodeUUID *string `json:"center_node_uuid,omitempty" url:"-"`
	// one of user_id or group_id must be provided
	GroupID *string `json:"group_id,omitempty" url:"-"`
	// The maximum number of facts to retrieve. Defaults to 10. Limited to 50.
	Limit *int `json:"limit,omitempty" url:"-"`
	// The minimum rating by which to filter relevant facts
	MinFactRating *float64 `json:"min_fact_rating,omitempty" url:"-"`
	// Deprecated
	MinScore *float64 `json:"min_score,omitempty" url:"-"`
	// weighting for maximal marginal relevance
	MmrLambda *float64 `json:"mmr_lambda,omitempty" url:"-"`
	// The string to search for (required)
	Query string `json:"query" url:"-"`
	// Defaults to RRF
	Reranker *Reranker `json:"reranker,omitempty" url:"-"`
	// Defaults to Edges. Communities will be added in the future.
	Scope *GraphSearchScope `json:"scope,omitempty" url:"-"`
	// Search filters to apply to the search
	SearchFilters *SearchFilters `json:"search_filters,omitempty" url:"-"`
	// one of user_id or group_id must be provided
	UserID *string `json:"user_id,omitempty" url:"-"`
}

type EntityTypeRequest struct {
	EdgeTypes   []*EdgeType   `json:"edge_types,omitempty" url:"-"`
	EntityTypes []*EntityType `json:"entity_types,omitempty" url:"-"`
}

type AddTripleResponse struct {
	Edge       *EntityEdge `json:"edge,omitempty" url:"edge,omitempty"`
	SourceNode *EntityNode `json:"source_node,omitempty" url:"source_node,omitempty"`
	TargetNode *EntityNode `json:"target_node,omitempty" url:"target_node,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AddTripleResponse) GetEdge() *EntityEdge {
	if a == nil {
		return nil
	}
	return a.Edge
}

func (a *AddTripleResponse) GetSourceNode() *EntityNode {
	if a == nil {
		return nil
	}
	return a.SourceNode
}

func (a *AddTripleResponse) GetTargetNode() *EntityNode {
	if a == nil {
		return nil
	}
	return a.TargetNode
}

func (a *AddTripleResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AddTripleResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AddTripleResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AddTripleResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AddTripleResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type EdgeType struct {
	Description   string                    `json:"description" url:"description"`
	Name          string                    `json:"name" url:"name"`
	Properties    []*EntityProperty         `json:"properties,omitempty" url:"properties,omitempty"`
	SourceTargets []*EntityEdgeSourceTarget `json:"source_targets,omitempty" url:"source_targets,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EdgeType) GetDescription() string {
	if e == nil {
		return ""
	}
	return e.Description
}

func (e *EdgeType) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EdgeType) GetProperties() []*EntityProperty {
	if e == nil {
		return nil
	}
	return e.Properties
}

func (e *EdgeType) GetSourceTargets() []*EntityEdgeSourceTarget {
	if e == nil {
		return nil
	}
	return e.SourceTargets
}

func (e *EdgeType) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EdgeType) UnmarshalJSON(data []byte) error {
	type unmarshaler EdgeType
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EdgeType(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EdgeType) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EntityEdgeSourceTarget struct {
	// Source represents the originating node identifier in the edge type relationship. (optional)
	Source *string `json:"source,omitempty" url:"source,omitempty"`
	// Target represents the target node identifier in the edge type relationship. (optional)
	Target *string `json:"target,omitempty" url:"target,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityEdgeSourceTarget) GetSource() *string {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *EntityEdgeSourceTarget) GetTarget() *string {
	if e == nil {
		return nil
	}
	return e.Target
}

func (e *EntityEdgeSourceTarget) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EntityEdgeSourceTarget) UnmarshalJSON(data []byte) error {
	type unmarshaler EntityEdgeSourceTarget
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EntityEdgeSourceTarget(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityEdgeSourceTarget) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EntityProperty struct {
	Description string             `json:"description" url:"description"`
	Name        string             `json:"name" url:"name"`
	Type        EntityPropertyType `json:"type" url:"type"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityProperty) GetDescription() string {
	if e == nil {
		return ""
	}
	return e.Description
}

func (e *EntityProperty) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EntityProperty) GetType() EntityPropertyType {
	if e == nil {
		return ""
	}
	return e.Type
}

func (e *EntityProperty) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EntityProperty) UnmarshalJSON(data []byte) error {
	type unmarshaler EntityProperty
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EntityProperty(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityProperty) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EntityPropertyType string

const (
	EntityPropertyTypeText    EntityPropertyType = "Text"
	EntityPropertyTypeInt     EntityPropertyType = "Int"
	EntityPropertyTypeFloat   EntityPropertyType = "Float"
	EntityPropertyTypeBoolean EntityPropertyType = "Boolean"
)

func NewEntityPropertyTypeFromString(s string) (EntityPropertyType, error) {
	switch s {
	case "Text":
		return EntityPropertyTypeText, nil
	case "Int":
		return EntityPropertyTypeInt, nil
	case "Float":
		return EntityPropertyTypeFloat, nil
	case "Boolean":
		return EntityPropertyTypeBoolean, nil
	}
	var t EntityPropertyType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e EntityPropertyType) Ptr() *EntityPropertyType {
	return &e
}

type EntityType struct {
	Description string            `json:"description" url:"description"`
	Name        string            `json:"name" url:"name"`
	Properties  []*EntityProperty `json:"properties,omitempty" url:"properties,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityType) GetDescription() string {
	if e == nil {
		return ""
	}
	return e.Description
}

func (e *EntityType) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EntityType) GetProperties() []*EntityProperty {
	if e == nil {
		return nil
	}
	return e.Properties
}

func (e *EntityType) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EntityType) UnmarshalJSON(data []byte) error {
	type unmarshaler EntityType
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EntityType(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityType) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EntityTypeResponse struct {
	EdgeTypes   []*EdgeType   `json:"edge_types,omitempty" url:"edge_types,omitempty"`
	EntityTypes []*EntityType `json:"entity_types,omitempty" url:"entity_types,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EntityTypeResponse) GetEdgeTypes() []*EdgeType {
	if e == nil {
		return nil
	}
	return e.EdgeTypes
}

func (e *EntityTypeResponse) GetEntityTypes() []*EntityType {
	if e == nil {
		return nil
	}
	return e.EntityTypes
}

func (e *EntityTypeResponse) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EntityTypeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EntityTypeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EntityTypeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EntityTypeResponse) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EpisodeData struct {
	CreatedAt         *string       `json:"created_at,omitempty" url:"created_at,omitempty"`
	Data              string        `json:"data" url:"data"`
	SourceDescription *string       `json:"source_description,omitempty" url:"source_description,omitempty"`
	Type              GraphDataType `json:"type" url:"type"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EpisodeData) GetCreatedAt() *string {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *EpisodeData) GetData() string {
	if e == nil {
		return ""
	}
	return e.Data
}

func (e *EpisodeData) GetSourceDescription() *string {
	if e == nil {
		return nil
	}
	return e.SourceDescription
}

func (e *EpisodeData) GetType() GraphDataType {
	if e == nil {
		return ""
	}
	return e.Type
}

func (e *EpisodeData) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EpisodeData) UnmarshalJSON(data []byte) error {
	type unmarshaler EpisodeData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EpisodeData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EpisodeData) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type GraphSearchScope string

const (
	GraphSearchScopeEdges    GraphSearchScope = "edges"
	GraphSearchScopeNodes    GraphSearchScope = "nodes"
	GraphSearchScopeEpisodes GraphSearchScope = "episodes"
)

func NewGraphSearchScopeFromString(s string) (GraphSearchScope, error) {
	switch s {
	case "edges":
		return GraphSearchScopeEdges, nil
	case "nodes":
		return GraphSearchScopeNodes, nil
	case "episodes":
		return GraphSearchScopeEpisodes, nil
	}
	var t GraphSearchScope
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GraphSearchScope) Ptr() *GraphSearchScope {
	return &g
}

type Reranker string

const (
	RerankerRrf             Reranker = "rrf"
	RerankerMmr             Reranker = "mmr"
	RerankerNodeDistance    Reranker = "node_distance"
	RerankerEpisodeMentions Reranker = "episode_mentions"
	RerankerCrossEncoder    Reranker = "cross_encoder"
)

func NewRerankerFromString(s string) (Reranker, error) {
	switch s {
	case "rrf":
		return RerankerRrf, nil
	case "mmr":
		return RerankerMmr, nil
	case "node_distance":
		return RerankerNodeDistance, nil
	case "episode_mentions":
		return RerankerEpisodeMentions, nil
	case "cross_encoder":
		return RerankerCrossEncoder, nil
	}
	var t Reranker
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r Reranker) Ptr() *Reranker {
	return &r
}

type SearchFilters struct {
	// List of edge types to filter on
	EdgeTypes []string `json:"edge_types,omitempty" url:"edge_types,omitempty"`
	// List of node labels to filter on
	NodeLabels []string `json:"node_labels,omitempty" url:"node_labels,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SearchFilters) GetEdgeTypes() []string {
	if s == nil {
		return nil
	}
	return s.EdgeTypes
}

func (s *SearchFilters) GetNodeLabels() []string {
	if s == nil {
		return nil
	}
	return s.NodeLabels
}

func (s *SearchFilters) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SearchFilters) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchFilters
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SearchFilters(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SearchFilters) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
