// Code generated by Fern. DO NOT EDIT.

package zep

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/getzep/zep-go/v4/internal"
)

type UserGroupAddMembersRequest struct {
	// Project UUID
	ProjectID string                         `json:"-" url:"projectId"`
	Body      *MutateUserGroupMembersRequest `json:"-" url:"-"`
}

func (u *UserGroupAddMembersRequest) UnmarshalJSON(data []byte) error {
	body := new(MutateUserGroupMembersRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UserGroupAddMembersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

type AttachPolicySetRequest struct {
	// Project UUID
	ProjectID     string `json:"-" url:"projectId"`
	PolicySetUUID string `json:"policy_set_uuid" url:"-"`
}

type CreateUserGroupRequest struct {
	// Project UUID
	ProjectID   string  `json:"-" url:"projectId"`
	Description *string `json:"description,omitempty" url:"-"`
	Name        string  `json:"name" url:"-"`
}

type UserGroupDeleteRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
}

type UserGroupDetachPolicySetRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
}

type UserGroupGetRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
}

type UserGroupListRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
	// Page number
	PageNumber int `json:"-" url:"pageNumber"`
	// Page size
	PageSize int `json:"-" url:"pageSize"`
	// Name search
	Search *string `json:"-" url:"search,omitempty"`
}

type UserGroupListForUserRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
}

type UserGroupListMemberCandidatesRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
	// Page number
	PageNumber int `json:"-" url:"pageNumber"`
	// Page size
	PageSize int `json:"-" url:"pageSize"`
	// User search
	Search *string `json:"-" url:"search,omitempty"`
}

type UserGroupListMembersRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
	// Page number
	PageNumber int `json:"-" url:"pageNumber"`
	// Page size
	PageSize int `json:"-" url:"pageSize"`
	// User search
	Search *string `json:"-" url:"search,omitempty"`
}

type UserGroupListPolicySetsRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
}

type UserGroupRemoveMemberRequest struct {
	// Project UUID
	ProjectID string `json:"-" url:"projectId"`
}

type UserGroupRemoveMembersRequest struct {
	// Project UUID
	ProjectID string                         `json:"-" url:"projectId"`
	Body      *MutateUserGroupMembersRequest `json:"-" url:"-"`
}

func (u *UserGroupRemoveMembersRequest) UnmarshalJSON(data []byte) error {
	body := new(MutateUserGroupMembersRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	u.Body = body
	return nil
}

func (u *UserGroupRemoveMembersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.Body)
}

type AttachedPolicySetsResponse struct {
	PolicySets []*PolicySetSummaryResponse `json:"policy_sets,omitempty" url:"policy_sets,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AttachedPolicySetsResponse) GetPolicySets() []*PolicySetSummaryResponse {
	if a == nil {
		return nil
	}
	return a.PolicySets
}

func (a *AttachedPolicySetsResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AttachedPolicySetsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler AttachedPolicySetsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AttachedPolicySetsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AttachedPolicySetsResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type MutateUserGroupMembersRequest struct {
	UserUUIDs []string `json:"user_uuids" url:"user_uuids"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MutateUserGroupMembersRequest) GetUserUUIDs() []string {
	if m == nil {
		return nil
	}
	return m.UserUUIDs
}

func (m *MutateUserGroupMembersRequest) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MutateUserGroupMembersRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MutateUserGroupMembersRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MutateUserGroupMembersRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MutateUserGroupMembersRequest) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type PolicySetSummaryResponse struct {
	Mode    *string `json:"mode,omitempty" url:"mode,omitempty"`
	Name    *string `json:"name,omitempty" url:"name,omitempty"`
	UUID    *string `json:"uuid,omitempty" url:"uuid,omitempty"`
	Version *int    `json:"version,omitempty" url:"version,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PolicySetSummaryResponse) GetMode() *string {
	if p == nil {
		return nil
	}
	return p.Mode
}

func (p *PolicySetSummaryResponse) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PolicySetSummaryResponse) GetUUID() *string {
	if p == nil {
		return nil
	}
	return p.UUID
}

func (p *PolicySetSummaryResponse) GetVersion() *int {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PolicySetSummaryResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PolicySetSummaryResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PolicySetSummaryResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PolicySetSummaryResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PolicySetSummaryResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type UserGroup struct {
	AttachedPolicySetCount *int           `json:"attached_policy_set_count,omitempty" url:"attached_policy_set_count,omitempty"`
	CreatedAt              *string        `json:"created_at,omitempty" url:"created_at,omitempty"`
	Description            *string        `json:"description,omitempty" url:"description,omitempty"`
	Kind                   *UserGroupKind `json:"kind,omitempty" url:"kind,omitempty"`
	MemberCount            *int           `json:"member_count,omitempty" url:"member_count,omitempty"`
	Name                   *string        `json:"name,omitempty" url:"name,omitempty"`
	ProjectUUID            *string        `json:"project_uuid,omitempty" url:"project_uuid,omitempty"`
	UpdatedAt              *string        `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	UUID                   *string        `json:"uuid,omitempty" url:"uuid,omitempty"`
	Version                *int           `json:"version,omitempty" url:"version,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserGroup) GetAttachedPolicySetCount() *int {
	if u == nil {
		return nil
	}
	return u.AttachedPolicySetCount
}

func (u *UserGroup) GetCreatedAt() *string {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserGroup) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UserGroup) GetKind() *UserGroupKind {
	if u == nil {
		return nil
	}
	return u.Kind
}

func (u *UserGroup) GetMemberCount() *int {
	if u == nil {
		return nil
	}
	return u.MemberCount
}

func (u *UserGroup) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UserGroup) GetProjectUUID() *string {
	if u == nil {
		return nil
	}
	return u.ProjectUUID
}

func (u *UserGroup) GetUpdatedAt() *string {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

func (u *UserGroup) GetUUID() *string {
	if u == nil {
		return nil
	}
	return u.UUID
}

func (u *UserGroup) GetVersion() *int {
	if u == nil {
		return nil
	}
	return u.Version
}

func (u *UserGroup) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UserGroup) UnmarshalJSON(data []byte) error {
	type unmarshaler UserGroup
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserGroup(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserGroup) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UserGroupKind string

const (
	UserGroupKindManaged UserGroupKind = "managed"
	UserGroupKindVirtual UserGroupKind = "virtual"
)

func NewUserGroupKindFromString(s string) (UserGroupKind, error) {
	switch s {
	case "managed":
		return UserGroupKindManaged, nil
	case "virtual":
		return UserGroupKindVirtual, nil
	}
	var t UserGroupKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UserGroupKind) Ptr() *UserGroupKind {
	return &u
}

type UserGroupListResponse struct {
	Quota      *UserGroupQuota `json:"quota,omitempty" url:"quota,omitempty"`
	RowCount   *int            `json:"row_count,omitempty" url:"row_count,omitempty"`
	TotalCount *int            `json:"total_count,omitempty" url:"total_count,omitempty"`
	UserGroups []*UserGroup    `json:"user_groups,omitempty" url:"user_groups,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserGroupListResponse) GetQuota() *UserGroupQuota {
	if u == nil {
		return nil
	}
	return u.Quota
}

func (u *UserGroupListResponse) GetRowCount() *int {
	if u == nil {
		return nil
	}
	return u.RowCount
}

func (u *UserGroupListResponse) GetTotalCount() *int {
	if u == nil {
		return nil
	}
	return u.TotalCount
}

func (u *UserGroupListResponse) GetUserGroups() []*UserGroup {
	if u == nil {
		return nil
	}
	return u.UserGroups
}

func (u *UserGroupListResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UserGroupListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UserGroupListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserGroupListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserGroupListResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UserGroupMembersResponse struct {
	RowCount   *int    `json:"row_count,omitempty" url:"row_count,omitempty"`
	TotalCount *int    `json:"total_count,omitempty" url:"total_count,omitempty"`
	Users      []*User `json:"users,omitempty" url:"users,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserGroupMembersResponse) GetRowCount() *int {
	if u == nil {
		return nil
	}
	return u.RowCount
}

func (u *UserGroupMembersResponse) GetTotalCount() *int {
	if u == nil {
		return nil
	}
	return u.TotalCount
}

func (u *UserGroupMembersResponse) GetUsers() []*User {
	if u == nil {
		return nil
	}
	return u.Users
}

func (u *UserGroupMembersResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UserGroupMembersResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UserGroupMembersResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserGroupMembersResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserGroupMembersResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UserGroupMembershipResponse struct {
	AddedCount   *int `json:"added_count,omitempty" url:"added_count,omitempty"`
	NoOpCount    *int `json:"no_op_count,omitempty" url:"no_op_count,omitempty"`
	RemovedCount *int `json:"removed_count,omitempty" url:"removed_count,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserGroupMembershipResponse) GetAddedCount() *int {
	if u == nil {
		return nil
	}
	return u.AddedCount
}

func (u *UserGroupMembershipResponse) GetNoOpCount() *int {
	if u == nil {
		return nil
	}
	return u.NoOpCount
}

func (u *UserGroupMembershipResponse) GetRemovedCount() *int {
	if u == nil {
		return nil
	}
	return u.RemovedCount
}

func (u *UserGroupMembershipResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UserGroupMembershipResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UserGroupMembershipResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserGroupMembershipResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserGroupMembershipResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UserGroupQuota struct {
	ActiveManaged *int  `json:"active_managed,omitempty" url:"active_managed,omitempty"`
	Allocation    *int  `json:"allocation,omitempty" url:"allocation,omitempty"`
	HasFeature    *bool `json:"has_feature,omitempty" url:"has_feature,omitempty"`
	Resolved      *bool `json:"resolved,omitempty" url:"resolved,omitempty"`
	Unlimited     *bool `json:"unlimited,omitempty" url:"unlimited,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserGroupQuota) GetActiveManaged() *int {
	if u == nil {
		return nil
	}
	return u.ActiveManaged
}

func (u *UserGroupQuota) GetAllocation() *int {
	if u == nil {
		return nil
	}
	return u.Allocation
}

func (u *UserGroupQuota) GetHasFeature() *bool {
	if u == nil {
		return nil
	}
	return u.HasFeature
}

func (u *UserGroupQuota) GetResolved() *bool {
	if u == nil {
		return nil
	}
	return u.Resolved
}

func (u *UserGroupQuota) GetUnlimited() *bool {
	if u == nil {
		return nil
	}
	return u.Unlimited
}

func (u *UserGroupQuota) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UserGroupQuota) UnmarshalJSON(data []byte) error {
	type unmarshaler UserGroupQuota
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserGroupQuota(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserGroupQuota) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UserGroupResponse struct {
	AttachedPolicySetCount *int           `json:"attached_policy_set_count,omitempty" url:"attached_policy_set_count,omitempty"`
	CreatedAt              *string        `json:"created_at,omitempty" url:"created_at,omitempty"`
	Description            *string        `json:"description,omitempty" url:"description,omitempty"`
	Kind                   *UserGroupKind `json:"kind,omitempty" url:"kind,omitempty"`
	MemberCount            *int           `json:"member_count,omitempty" url:"member_count,omitempty"`
	Name                   *string        `json:"name,omitempty" url:"name,omitempty"`
	ProjectUUID            *string        `json:"project_uuid,omitempty" url:"project_uuid,omitempty"`
	UpdatedAt              *string        `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	UUID                   *string        `json:"uuid,omitempty" url:"uuid,omitempty"`
	Version                *int           `json:"version,omitempty" url:"version,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserGroupResponse) GetAttachedPolicySetCount() *int {
	if u == nil {
		return nil
	}
	return u.AttachedPolicySetCount
}

func (u *UserGroupResponse) GetCreatedAt() *string {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserGroupResponse) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UserGroupResponse) GetKind() *UserGroupKind {
	if u == nil {
		return nil
	}
	return u.Kind
}

func (u *UserGroupResponse) GetMemberCount() *int {
	if u == nil {
		return nil
	}
	return u.MemberCount
}

func (u *UserGroupResponse) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UserGroupResponse) GetProjectUUID() *string {
	if u == nil {
		return nil
	}
	return u.ProjectUUID
}

func (u *UserGroupResponse) GetUpdatedAt() *string {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}

func (u *UserGroupResponse) GetUUID() *string {
	if u == nil {
		return nil
	}
	return u.UUID
}

func (u *UserGroupResponse) GetVersion() *int {
	if u == nil {
		return nil
	}
	return u.Version
}

func (u *UserGroupResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UserGroupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UserGroupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserGroupResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserGroupResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UserMembershipGroupsResponse struct {
	UserGroups []*UserGroup `json:"user_groups,omitempty" url:"user_groups,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UserMembershipGroupsResponse) GetUserGroups() []*UserGroup {
	if u == nil {
		return nil
	}
	return u.UserGroups
}

func (u *UserMembershipGroupsResponse) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UserMembershipGroupsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UserMembershipGroupsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UserMembershipGroupsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UserMembershipGroupsResponse) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateUserGroupRequest struct {
	// Project UUID
	ProjectID       string  `json:"-" url:"projectId"`
	Description     *string `json:"description,omitempty" url:"-"`
	ExpectedVersion int     `json:"expected_version" url:"-"`
	Name            *string `json:"name,omitempty" url:"-"`
}
