// Code generated by Fern. DO NOT EDIT.

package graph

import (
	json "encoding/json"
	fmt "fmt"
	v4 "github.com/getzep/zep-go/v4"
	internal "github.com/getzep/zep-go/v4/internal"
	big "math/big"
)

var (
	addNodesRequestFieldNodes = big.NewInt(1 << 0)
)

type AddNodesRequest struct {
	// The nodes to add to the graph.
	Nodes []*v4.NodeInput `json:"nodes" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AddNodesRequest) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetNodes sets the Nodes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AddNodesRequest) SetNodes(nodes []*v4.NodeInput) {
	a.Nodes = nodes
	a.require(addNodesRequestFieldNodes)
}

func (a *AddNodesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AddNodesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AddNodesRequest(body)
	return nil
}

func (a *AddNodesRequest) MarshalJSON() ([]byte, error) {
	type embed AddNodesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	nodeListRequestFieldLimit   = big.NewInt(1 << 0)
	nodeListRequestFieldCursor  = big.NewInt(1 << 1)
	nodeListRequestFieldOrderBy = big.NewInt(1 << 2)
	nodeListRequestFieldOrder   = big.NewInt(1 << 3)
)

type NodeListRequest struct {
	// Page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Sort key: uuid (default) or degree
	OrderBy *NodeListRequestOrderBy `json:"-" url:"order_by,omitempty"`
	// Sort direction: asc or desc (default desc)
	Order *NodeListRequestOrder   `json:"-" url:"order,omitempty"`
	Body  *v4.ArtifactListRequest `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (n *NodeListRequest) require(field *big.Int) {
	next := new(big.Int)
	if n.explicitFields != nil {
		next.Set(n.explicitFields)
	}
	next.Or(next, field)
	n.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NodeListRequest) SetLimit(limit *int) {
	n.Limit = limit
	n.require(nodeListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NodeListRequest) SetCursor(cursor *string) {
	n.Cursor = cursor
	n.require(nodeListRequestFieldCursor)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NodeListRequest) SetOrderBy(orderBy *NodeListRequestOrderBy) {
	n.OrderBy = orderBy
	n.require(nodeListRequestFieldOrderBy)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NodeListRequest) SetOrder(order *NodeListRequestOrder) {
	n.Order = order
	n.require(nodeListRequestFieldOrder)
}

func (n *NodeListRequest) UnmarshalJSON(data []byte) error {
	body := new(v4.ArtifactListRequest)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.Body = body
	return nil
}

func (n *NodeListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}

var (
	neighborsRequestFieldLimit     = big.NewInt(1 << 0)
	neighborsRequestFieldCursor    = big.NewInt(1 << 1)
	neighborsRequestFieldOrderBy   = big.NewInt(1 << 2)
	neighborsRequestFieldOrder     = big.NewInt(1 << 3)
	neighborsRequestFieldDirection = big.NewInt(1 << 4)
	neighborsRequestFieldFilters   = big.NewInt(1 << 5)
)

type NeighborsRequest struct {
	// Page size
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// Sort field
	OrderBy *NodeListNeighborsRequestOrderBy `json:"-" url:"order_by,omitempty"`
	// Sort direction: asc or desc
	Order *NodeListNeighborsRequestOrder `json:"-" url:"order,omitempty"`
	// The edge orientation to follow from the node: in, out, or both.
	Direction *NeighborsRequestDirection `json:"direction,omitempty" url:"-"`
	// Filters constraining the connecting edges and the neighbor nodes.
	Filters *v4.SearchFilters `json:"filters,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (n *NeighborsRequest) require(field *big.Int) {
	next := new(big.Int)
	if n.explicitFields != nil {
		next.Set(n.explicitFields)
	}
	next.Or(next, field)
	n.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NeighborsRequest) SetLimit(limit *int) {
	n.Limit = limit
	n.require(neighborsRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NeighborsRequest) SetCursor(cursor *string) {
	n.Cursor = cursor
	n.require(neighborsRequestFieldCursor)
}

// SetOrderBy sets the OrderBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NeighborsRequest) SetOrderBy(orderBy *NodeListNeighborsRequestOrderBy) {
	n.OrderBy = orderBy
	n.require(neighborsRequestFieldOrderBy)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NeighborsRequest) SetOrder(order *NodeListNeighborsRequestOrder) {
	n.Order = order
	n.require(neighborsRequestFieldOrder)
}

// SetDirection sets the Direction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NeighborsRequest) SetDirection(direction *NeighborsRequestDirection) {
	n.Direction = direction
	n.require(neighborsRequestFieldDirection)
}

// SetFilters sets the Filters field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NeighborsRequest) SetFilters(filters *v4.SearchFilters) {
	n.Filters = filters
	n.require(neighborsRequestFieldFilters)
}

func (n *NeighborsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler NeighborsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*n = NeighborsRequest(body)
	return nil
}

func (n *NeighborsRequest) MarshalJSON() ([]byte, error) {
	type embed NeighborsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// The edge orientation to follow from the node: in, out, or both.
type NeighborsRequestDirection string

const (
	NeighborsRequestDirectionIn   NeighborsRequestDirection = "in"
	NeighborsRequestDirectionOut  NeighborsRequestDirection = "out"
	NeighborsRequestDirectionBoth NeighborsRequestDirection = "both"
)

func NewNeighborsRequestDirectionFromString(s string) (NeighborsRequestDirection, error) {
	switch s {
	case "in":
		return NeighborsRequestDirectionIn, nil
	case "out":
		return NeighborsRequestDirectionOut, nil
	case "both":
		return NeighborsRequestDirectionBoth, nil
	}
	var t NeighborsRequestDirection
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (n NeighborsRequestDirection) Ptr() *NeighborsRequestDirection {
	return &n
}

type NodeListNeighborsRequestOrder string

const (
	NodeListNeighborsRequestOrderAsc  NodeListNeighborsRequestOrder = "asc"
	NodeListNeighborsRequestOrderDesc NodeListNeighborsRequestOrder = "desc"
)

func NewNodeListNeighborsRequestOrderFromString(s string) (NodeListNeighborsRequestOrder, error) {
	switch s {
	case "asc":
		return NodeListNeighborsRequestOrderAsc, nil
	case "desc":
		return NodeListNeighborsRequestOrderDesc, nil
	}
	var t NodeListNeighborsRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (n NodeListNeighborsRequestOrder) Ptr() *NodeListNeighborsRequestOrder {
	return &n
}

type NodeListNeighborsRequestOrderBy string

const (
	NodeListNeighborsRequestOrderByUUID      NodeListNeighborsRequestOrderBy = "uuid"
	NodeListNeighborsRequestOrderByCreatedAt NodeListNeighborsRequestOrderBy = "created_at"
)

func NewNodeListNeighborsRequestOrderByFromString(s string) (NodeListNeighborsRequestOrderBy, error) {
	switch s {
	case "uuid":
		return NodeListNeighborsRequestOrderByUUID, nil
	case "created_at":
		return NodeListNeighborsRequestOrderByCreatedAt, nil
	}
	var t NodeListNeighborsRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (n NodeListNeighborsRequestOrderBy) Ptr() *NodeListNeighborsRequestOrderBy {
	return &n
}

type NodeListRequestOrder string

const (
	NodeListRequestOrderAsc  NodeListRequestOrder = "asc"
	NodeListRequestOrderDesc NodeListRequestOrder = "desc"
)

func NewNodeListRequestOrderFromString(s string) (NodeListRequestOrder, error) {
	switch s {
	case "asc":
		return NodeListRequestOrderAsc, nil
	case "desc":
		return NodeListRequestOrderDesc, nil
	}
	var t NodeListRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (n NodeListRequestOrder) Ptr() *NodeListRequestOrder {
	return &n
}

type NodeListRequestOrderBy string

const (
	NodeListRequestOrderByUUID   NodeListRequestOrderBy = "uuid"
	NodeListRequestOrderByDegree NodeListRequestOrderBy = "degree"
)

func NewNodeListRequestOrderByFromString(s string) (NodeListRequestOrderBy, error) {
	switch s {
	case "uuid":
		return NodeListRequestOrderByUUID, nil
	case "degree":
		return NodeListRequestOrderByDegree, nil
	}
	var t NodeListRequestOrderBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (n NodeListRequestOrderBy) Ptr() *NodeListRequestOrderBy {
	return &n
}

var (
	patchNodeRequestFieldAttributes = big.NewInt(1 << 0)
	patchNodeRequestFieldName       = big.NewInt(1 << 1)
	patchNodeRequestFieldSummary    = big.NewInt(1 << 2)
)

type PatchNodeRequest struct {
	// Additional attributes to merge onto the node; a key set to null is
	// removed.
	Attributes map[string]any `json:"attributes,omitempty" url:"-"`
	// The node's name.
	Name *string `json:"name,omitempty" url:"-"`
	// A summary of the node.
	Summary *string `json:"summary,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PatchNodeRequest) require(field *big.Int) {
	next := new(big.Int)
	if p.explicitFields != nil {
		next.Set(p.explicitFields)
	}
	next.Or(next, field)
	p.explicitFields = next
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchNodeRequest) SetAttributes(attributes map[string]any) {
	p.Attributes = attributes
	p.require(patchNodeRequestFieldAttributes)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchNodeRequest) SetName(name *string) {
	p.Name = name
	p.require(patchNodeRequestFieldName)
}

// SetSummary sets the Summary field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchNodeRequest) SetSummary(summary *string) {
	p.Summary = summary
	p.require(patchNodeRequestFieldSummary)
}

func (p *PatchNodeRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PatchNodeRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PatchNodeRequest(body)
	return nil
}

func (p *PatchNodeRequest) MarshalJSON() ([]byte, error) {
	type embed PatchNodeRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}
