// Code generated by Fern. DO NOT EDIT.

package context

import (
	context "context"
	v2 "github.com/getzep/zep-go/v2"
	core "github.com/getzep/zep-go/v2/core"
	internal "github.com/getzep/zep-go/v2/internal"
	option "github.com/getzep/zep-go/v2/option"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("ZEP_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Lists all context templates.
func (c *Client) ListContextTemplates(
	ctx context.Context,
	opts ...option.RequestOption,
) (*v2.ListContextTemplatesResponse, error) {
	response, err := c.WithRawResponse.ListContextTemplates(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new context template.
func (c *Client) CreateContextTemplate(
	ctx context.Context,
	request *v2.CreateContextTemplateRequest,
	opts ...option.RequestOption,
) (*v2.ContextTemplateResponse, error) {
	response, err := c.WithRawResponse.CreateContextTemplate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves a context template by template_id.
func (c *Client) GetContextTemplate(
	ctx context.Context,
	// Template ID
	templateID string,
	opts ...option.RequestOption,
) (*v2.ContextTemplateResponse, error) {
	response, err := c.WithRawResponse.GetContextTemplate(
		ctx,
		templateID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates an existing context template by template_id.
func (c *Client) UpdateContextTemplate(
	ctx context.Context,
	// Template ID
	templateID string,
	request *v2.UpdateContextTemplateRequest,
	opts ...option.RequestOption,
) (*v2.ContextTemplateResponse, error) {
	response, err := c.WithRawResponse.UpdateContextTemplate(
		ctx,
		templateID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes a context template by template_id.
func (c *Client) DeleteContextTemplate(
	ctx context.Context,
	// Template ID
	templateID string,
	opts ...option.RequestOption,
) (*v2.SuccessResponse, error) {
	response, err := c.WithRawResponse.DeleteContextTemplate(
		ctx,
		templateID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
