// Code generated by Fern. DO NOT EDIT.

package edge

import (
	context "context"
	v2 "github.com/getzep/zep-go/v2"
	core "github.com/getzep/zep-go/v2/core"
	graph "github.com/getzep/zep-go/v2/graph"
	internal "github.com/getzep/zep-go/v2/internal"
	option "github.com/getzep/zep-go/v2/option"
	http "net/http"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	if options.APIKey == "" {
		options.APIKey = os.Getenv("ZEP_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

// Returns all edges for a graph.
func (c *Client) GetByGraphID(
	ctx context.Context,
	// Graph ID
	graphID string,
	request *v2.GraphEdgesRequest,
	opts ...option.RequestOption,
) ([]*v2.EntityEdge, error) {
	response, err := c.WithRawResponse.GetByGraphID(
		ctx,
		graphID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns all edges for a user.
func (c *Client) GetByUserID(
	ctx context.Context,
	// User ID
	userID string,
	request *v2.GraphEdgesRequest,
	opts ...option.RequestOption,
) ([]*v2.EntityEdge, error) {
	response, err := c.WithRawResponse.GetByUserID(
		ctx,
		userID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a specific edge by its UUID.
func (c *Client) Get(
	ctx context.Context,
	// Edge UUID
	uuid string,
	opts ...option.RequestOption,
) (*v2.EntityEdge, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		uuid,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Deletes an edge by UUID.
func (c *Client) Delete(
	ctx context.Context,
	// Edge UUID
	uuid string,
	opts ...option.RequestOption,
) (*v2.SuccessResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		uuid,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates an entity edge by UUID.
func (c *Client) Update(
	ctx context.Context,
	// Edge UUID
	uuid string,
	request *graph.UpdateEdgeRequest,
	opts ...option.RequestOption,
) (*v2.EntityEdge, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		uuid,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
