// Code generated by Fern. DO NOT EDIT.

package agent

import (
	json "encoding/json"
	fmt "fmt"
	v4 "github.com/getzep/zep-go/v4"
	internal "github.com/getzep/zep-go/v4/internal"
	big "math/big"
)

var (
	approveAgentSkillRequestFieldExpectedVersion = big.NewInt(1 << 0)
)

type ApproveAgentSkillRequest struct {
	ExpectedVersion int `json:"expected_version" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *ApproveAgentSkillRequest) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetExpectedVersion sets the ExpectedVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApproveAgentSkillRequest) SetExpectedVersion(expectedVersion int) {
	a.ExpectedVersion = expectedVersion
	a.require(approveAgentSkillRequestFieldExpectedVersion)
}

func (a *ApproveAgentSkillRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ApproveAgentSkillRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = ApproveAgentSkillRequest(body)
	return nil
}

func (a *ApproveAgentSkillRequest) MarshalJSON() ([]byte, error) {
	type embed ApproveAgentSkillRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createAgentSkillRequestFieldDefinition = big.NewInt(1 << 0)
	createAgentSkillRequestFieldSkillID    = big.NewInt(1 << 1)
)

type CreateAgentSkillRequest struct {
	Definition *v4.SkillDefinition `json:"definition" url:"-"`
	SkillID    *string             `json:"skill_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateAgentSkillRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentSkillRequest) SetDefinition(definition *v4.SkillDefinition) {
	c.Definition = definition
	c.require(createAgentSkillRequestFieldDefinition)
}

// SetSkillID sets the SkillID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentSkillRequest) SetSkillID(skillID *string) {
	c.SkillID = skillID
	c.require(createAgentSkillRequestFieldSkillID)
}

func (c *CreateAgentSkillRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateAgentSkillRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateAgentSkillRequest(body)
	return nil
}

func (c *CreateAgentSkillRequest) MarshalJSON() ([]byte, error) {
	type embed CreateAgentSkillRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createAgentSkillVersionRequestFieldDefinition      = big.NewInt(1 << 0)
	createAgentSkillVersionRequestFieldExpectedVersion = big.NewInt(1 << 1)
)

type CreateAgentSkillVersionRequest struct {
	Definition      *v4.SkillDefinition `json:"definition" url:"-"`
	ExpectedVersion int                 `json:"expected_version" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateAgentSkillVersionRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetDefinition sets the Definition field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentSkillVersionRequest) SetDefinition(definition *v4.SkillDefinition) {
	c.Definition = definition
	c.require(createAgentSkillVersionRequestFieldDefinition)
}

// SetExpectedVersion sets the ExpectedVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateAgentSkillVersionRequest) SetExpectedVersion(expectedVersion int) {
	c.ExpectedVersion = expectedVersion
	c.require(createAgentSkillVersionRequestFieldExpectedVersion)
}

func (c *CreateAgentSkillVersionRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateAgentSkillVersionRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateAgentSkillVersionRequest(body)
	return nil
}

func (c *CreateAgentSkillVersionRequest) MarshalJSON() ([]byte, error) {
	type embed CreateAgentSkillVersionRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	agentSkillListRequestFieldLimit        = big.NewInt(1 << 0)
	agentSkillListRequestFieldCursor       = big.NewInt(1 << 1)
	agentSkillListRequestFieldEnvironments = big.NewInt(1 << 2)
	agentSkillListRequestFieldKind         = big.NewInt(1 << 3)
	agentSkillListRequestFieldTaskFamily   = big.NewInt(1 << 4)
	agentSkillListRequestFieldTools        = big.NewInt(1 << 5)
)

type AgentSkillListRequest struct {
	// Page size (maximum 20)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor
	Cursor       *string  `json:"-" url:"cursor,omitempty"`
	Environments []string `json:"environments,omitempty" url:"-"`
	Kind         *string  `json:"kind,omitempty" url:"-"`
	TaskFamily   *string  `json:"task_family,omitempty" url:"-"`
	Tools        []string `json:"tools,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AgentSkillListRequest) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillListRequest) SetLimit(limit *int) {
	a.Limit = limit
	a.require(agentSkillListRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillListRequest) SetCursor(cursor *string) {
	a.Cursor = cursor
	a.require(agentSkillListRequestFieldCursor)
}

// SetEnvironments sets the Environments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillListRequest) SetEnvironments(environments []string) {
	a.Environments = environments
	a.require(agentSkillListRequestFieldEnvironments)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillListRequest) SetKind(kind *string) {
	a.Kind = kind
	a.require(agentSkillListRequestFieldKind)
}

// SetTaskFamily sets the TaskFamily field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillListRequest) SetTaskFamily(taskFamily *string) {
	a.TaskFamily = taskFamily
	a.require(agentSkillListRequestFieldTaskFamily)
}

// SetTools sets the Tools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillListRequest) SetTools(tools []string) {
	a.Tools = tools
	a.require(agentSkillListRequestFieldTools)
}

func (a *AgentSkillListRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentSkillListRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AgentSkillListRequest(body)
	return nil
}

func (a *AgentSkillListRequest) MarshalJSON() ([]byte, error) {
	type embed AgentSkillListRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	retireAgentSkillRequestFieldExpectedVersion = big.NewInt(1 << 0)
)

type RetireAgentSkillRequest struct {
	ExpectedVersion int `json:"expected_version" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetireAgentSkillRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetExpectedVersion sets the ExpectedVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetireAgentSkillRequest) SetExpectedVersion(expectedVersion int) {
	r.ExpectedVersion = expectedVersion
	r.require(retireAgentSkillRequestFieldExpectedVersion)
}

func (r *RetireAgentSkillRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RetireAgentSkillRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RetireAgentSkillRequest(body)
	return nil
}

func (r *RetireAgentSkillRequest) MarshalJSON() ([]byte, error) {
	type embed RetireAgentSkillRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	agentSkillSearchRequestFieldLimit           = big.NewInt(1 << 0)
	agentSkillSearchRequestFieldCursor          = big.NewInt(1 << 1)
	agentSkillSearchRequestFieldEnvironments    = big.NewInt(1 << 2)
	agentSkillSearchRequestFieldIncludeMarkdown = big.NewInt(1 << 3)
	agentSkillSearchRequestFieldKind            = big.NewInt(1 << 4)
	agentSkillSearchRequestFieldMarkdownFormat  = big.NewInt(1 << 5)
	agentSkillSearchRequestFieldQuery           = big.NewInt(1 << 6)
	agentSkillSearchRequestFieldTaskFamily      = big.NewInt(1 << 7)
	agentSkillSearchRequestFieldTools           = big.NewInt(1 << 8)
)

type AgentSkillSearchRequest struct {
	// Page size (maximum 20)
	Limit *int `json:"-" url:"limit,omitempty"`
	// Opaque page cursor
	Cursor          *string  `json:"-" url:"cursor,omitempty"`
	Environments    []string `json:"environments,omitempty" url:"-"`
	IncludeMarkdown *bool    `json:"include_markdown,omitempty" url:"-"`
	Kind            *string  `json:"kind,omitempty" url:"-"`
	// MarkdownFormat selects the form of inline `markdown`. `agent` (the
	// default) returns the Skill text that an Agent needs: no evidence
	// markers, the description only in the frontmatter, and no empty
	// sections. `full` returns the stored SKILL.md with its evidence markers.
	MarkdownFormat *AgentSkillSearchRequestMarkdownFormat `json:"markdown_format,omitempty" url:"-"`
	Query          string                                 `json:"query" url:"-"`
	TaskFamily     *string                                `json:"task_family,omitempty" url:"-"`
	Tools          []string                               `json:"tools,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AgentSkillSearchRequest) require(field *big.Int) {
	next := new(big.Int)
	if a.explicitFields != nil {
		next.Set(a.explicitFields)
	}
	next.Or(next, field)
	a.explicitFields = next
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetLimit(limit *int) {
	a.Limit = limit
	a.require(agentSkillSearchRequestFieldLimit)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetCursor(cursor *string) {
	a.Cursor = cursor
	a.require(agentSkillSearchRequestFieldCursor)
}

// SetEnvironments sets the Environments field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetEnvironments(environments []string) {
	a.Environments = environments
	a.require(agentSkillSearchRequestFieldEnvironments)
}

// SetIncludeMarkdown sets the IncludeMarkdown field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetIncludeMarkdown(includeMarkdown *bool) {
	a.IncludeMarkdown = includeMarkdown
	a.require(agentSkillSearchRequestFieldIncludeMarkdown)
}

// SetKind sets the Kind field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetKind(kind *string) {
	a.Kind = kind
	a.require(agentSkillSearchRequestFieldKind)
}

// SetMarkdownFormat sets the MarkdownFormat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetMarkdownFormat(markdownFormat *AgentSkillSearchRequestMarkdownFormat) {
	a.MarkdownFormat = markdownFormat
	a.require(agentSkillSearchRequestFieldMarkdownFormat)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetQuery(query string) {
	a.Query = query
	a.require(agentSkillSearchRequestFieldQuery)
}

// SetTaskFamily sets the TaskFamily field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetTaskFamily(taskFamily *string) {
	a.TaskFamily = taskFamily
	a.require(agentSkillSearchRequestFieldTaskFamily)
}

// SetTools sets the Tools field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AgentSkillSearchRequest) SetTools(tools []string) {
	a.Tools = tools
	a.require(agentSkillSearchRequestFieldTools)
}

func (a *AgentSkillSearchRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AgentSkillSearchRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AgentSkillSearchRequest(body)
	return nil
}

func (a *AgentSkillSearchRequest) MarshalJSON() ([]byte, error) {
	type embed AgentSkillSearchRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// MarkdownFormat selects the form of inline `markdown`. `agent` (the
// default) returns the Skill text that an Agent needs: no evidence
// markers, the description only in the frontmatter, and no empty
// sections. `full` returns the stored SKILL.md with its evidence markers.
type AgentSkillSearchRequestMarkdownFormat string

const (
	AgentSkillSearchRequestMarkdownFormatAgent AgentSkillSearchRequestMarkdownFormat = "agent"
	AgentSkillSearchRequestMarkdownFormatFull  AgentSkillSearchRequestMarkdownFormat = "full"
)

func NewAgentSkillSearchRequestMarkdownFormatFromString(s string) (AgentSkillSearchRequestMarkdownFormat, error) {
	switch s {
	case "agent":
		return AgentSkillSearchRequestMarkdownFormatAgent, nil
	case "full":
		return AgentSkillSearchRequestMarkdownFormatFull, nil
	}
	var t AgentSkillSearchRequestMarkdownFormat
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AgentSkillSearchRequestMarkdownFormat) Ptr() *AgentSkillSearchRequestMarkdownFormat {
	return &a
}
