// Code generated by Fern. DO NOT EDIT.

package verifier

import (
	context "context"
	http "net/http"

	zep "github.com/getzep/zep-go/v4"
	agent "github.com/getzep/zep-go/v4/agent"
	core "github.com/getzep/zep-go/v4/core"
	internal "github.com/getzep/zep-go/v4/internal"
	option "github.com/getzep/zep-go/v4/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Get(
	ctx context.Context,
	// Agent UUID
	agentUUID string,
	// Verifier UUID
	verifierUUID string,
	opts ...option.RequestOption,
) (*core.Response[*zep.AgentVerifier], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.getzep.com/api/v4",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/verifiers/%v",
		agentUUID,
		verifierUUID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *zep.AgentVerifier
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(agent.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*zep.AgentVerifier]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	// Agent UUID
	agentUUID string,
	// Verifier UUID
	verifierUUID string,
	request *agent.PatchAgentVerifierRequest,
	opts ...option.IdempotentRequestOption,
) (*core.Response[*zep.AgentVerifier], error) {
	options := core.NewIdempotentRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.getzep.com/api/v4",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/verifiers/%v",
		agentUUID,
		verifierUUID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	core.SetIdempotencyKeyHeader(headers)

	var response *zep.AgentVerifier
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(agent.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*zep.AgentVerifier]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) InvalidateEvidence(
	ctx context.Context,
	// Agent UUID
	agentUUID string,
	// Verifier UUID
	verifierUUID string,
	request *agent.InvalidateAgentVerifierEvidenceRequest,
	opts ...option.IdempotentRequestOption,
) (*core.Response[*zep.AgentVerifierEvidenceInvalidationResult], error) {
	options := core.NewIdempotentRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.getzep.com/api/v4",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/verifiers/%v/invalidate-evidence",
		agentUUID,
		verifierUUID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	core.SetIdempotencyKeyHeader(headers)

	var response *zep.AgentVerifierEvidenceInvalidationResult
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(agent.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*zep.AgentVerifierEvidenceInvalidationResult]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Revoke(
	ctx context.Context,
	// Agent UUID
	agentUUID string,
	// Verifier UUID
	verifierUUID string,
	request *agent.RevokeAgentVerifierRequest,
	opts ...option.IdempotentRequestOption,
) (*core.Response[*zep.AgentVerifier], error) {
	options := core.NewIdempotentRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.getzep.com/api/v4",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/agents/%v/verifiers/%v/revoke",
		agentUUID,
		verifierUUID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	core.SetIdempotencyKeyHeader(headers)

	var response *zep.AgentVerifier
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(agent.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*zep.AgentVerifier]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
