// Code generated by Fern. DO NOT EDIT.

package export

import (
	context "context"
	io "io"
	os "os"

	zep "github.com/getzep/zep-go/v4"
	core "github.com/getzep/zep-go/v4/core"
	internal "github.com/getzep/zep-go/v4/internal"
	option "github.com/getzep/zep-go/v4/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.APIKey == "" {
		options.APIKey = os.Getenv("ZEP_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Example:
//
//	client.Agent.Skill.Export.Create(
//	    context.TODO(),
//	    "agent_uuid",
//	    "skill_uuid",
//	    1,
//	)
func (c *Client) Create(
	ctx context.Context,
	// Agent UUID
	agentUUID string,
	// Skill UUID
	skillUUID string,
	// Skill version
	version int,
	opts ...option.IdempotentRequestOption,
) (*zep.Task, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		agentUUID,
		skillUUID,
		version,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Example:
//
//	client.Agent.Skill.Export.Get(
//	    context.TODO(),
//	    "agent_uuid",
//	    "skill_uuid",
//	    1,
//	    "task_uuid",
//	)
func (c *Client) Get(
	ctx context.Context,
	// Agent UUID
	agentUUID string,
	// Skill UUID
	skillUUID string,
	// Skill version
	version int,
	// Export Task UUID
	taskUUID string,
	opts ...option.RequestOption,
) (io.Reader, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		agentUUID,
		skillUUID,
		version,
		taskUUID,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
