// Code generated by Fern. DO NOT EDIT.

package thread_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	zep "github.com/getzep/zep-go/v4"
	client "github.com/getzep/zep-go/v4/client"
	option "github.com/getzep/zep-go/v4/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestThreadListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &zep.ThreadListRequest{
		Limit: zep.Int(
			1,
		),
		Cursor: zep.String(
			"cursor",
		),
		OrderBy: zep.String(
			"order_by",
		),
		Order: zep.String(
			"order",
		),
		UserUUID: zep.String(
			"user_uuid",
		),
	}
	_, invocationErr := client.Thread.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadListWithWireMock", "GET", "/threads", map[string]interface{}{"limit": "1", "cursor": "cursor", "order_by": "order_by", "order": "order", "user_uuid": "user_uuid"}, 1)
}

func TestThreadCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &zep.CreateThreadRequest{}
	_, invocationErr := client.Thread.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadCreateWithWireMock", "POST", "/threads", nil, 1)
}

func TestThreadLookupWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &zep.LookupRequest{}
	_, invocationErr := client.Thread.Lookup(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadLookupWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadLookupWithWireMock", "POST", "/threads/lookup", nil, 1)
}

func TestThreadGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	_, invocationErr := client.Thread.Get(
		context.TODO(),
		"thread_uuid",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadGetWithWireMock", "GET", "/threads/thread_uuid", nil, 1)
}

func TestThreadDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	_, invocationErr := client.Thread.Delete(
		context.TODO(),
		"thread_uuid",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadDeleteWithWireMock", "DELETE", "/threads/thread_uuid", nil, 1)
}

func TestThreadGetContextWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &zep.ThreadGetContextRequest{
		TemplateUUID: zep.String(
			"template_uuid",
		),
	}
	_, invocationErr := client.Thread.GetContext(
		context.TODO(),
		"thread_uuid",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadGetContextWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadGetContextWithWireMock", "GET", "/threads/thread_uuid/context", map[string]interface{}{"template_uuid": "template_uuid"}, 1)
}

func TestThreadListEpisodesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &zep.ThreadListEpisodesRequest{
		Limit: zep.Int(
			1,
		),
		Cursor: zep.String(
			"cursor",
		),
	}
	_, invocationErr := client.Thread.ListEpisodes(
		context.TODO(),
		"thread_uuid",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadListEpisodesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadListEpisodesWithWireMock", "GET", "/threads/thread_uuid/episodes", map[string]interface{}{"limit": "1", "cursor": "cursor"}, 1)
}

func TestThreadListMessagesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &zep.ThreadListMessagesRequest{
		Limit: zep.Int(
			1,
		),
		Cursor: zep.String(
			"cursor",
		),
	}
	_, invocationErr := client.Thread.ListMessages(
		context.TODO(),
		"thread_uuid",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadListMessagesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadListMessagesWithWireMock", "GET", "/threads/thread_uuid/messages", map[string]interface{}{"limit": "1", "cursor": "cursor"}, 1)
}

func TestThreadAddMessagesWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &zep.AddMessagesRequest{}
	_, invocationErr := client.Thread.AddMessages(
		context.TODO(),
		"thread_uuid",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadAddMessagesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadAddMessagesWithWireMock", "POST", "/threads/thread_uuid/messages", nil, 1)
}

func TestThreadGetSummaryWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	_, invocationErr := client.Thread.GetSummary(
		context.TODO(),
		"thread_uuid",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestThreadGetSummaryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestThreadGetSummaryWithWireMock", "GET", "/threads/thread_uuid/summary", nil, 1)
}
